from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from pathlib import Path
import re

from app.models import AudioRecording, Contact, Property, PropertyContactLink


@dataclass
class DraftCandidate:
    property_id: str | None
    contact_id: str | None
    contact_role: str | None
    action_type: str
    title: str
    description: str | None
    starts_at: datetime | None
    ends_at: datetime | None
    due_at: datetime | None
    confidence_label: str
    unresolved_fields: list[str]
    source_line: str


def build_stub_transcript(recording: AudioRecording, provider: str) -> str:
    example_name = Path(recording.original_filename).stem.replace("_", " ").replace("-", " ").strip() or "this call"
    return "\n".join(
        [
            f"Stub transcript generated by provider '{provider}' for {recording.original_filename}.",
            "No external transcription credits are configured yet.",
            "Replace this text in the review screen with the real call notes or transcript, then run extraction again.",
            "",
            f"Context hint: {example_name}.",
            "",
            "Example lines you can adapt:",
            "Buyer Maya Alvarez wants to visit Harbor House on 2026-06-01 at 15:30.",
            "Follow up with Maya Alvarez in 2 days about the purchase decision.",
            "Confirm the required documents with seller Ben Foster tomorrow.",
        ]
    )


def extract_draft_candidates(
    transcript_text: str,
    properties: list[Property],
    contacts: list[Contact],
    links: list[PropertyContactLink],
    now: datetime | None = None,
) -> tuple[list[DraftCandidate], dict[str, object]]:
    reference_time = now or datetime.now(UTC)
    lines = _candidate_lines(transcript_text)
    candidates: list[DraftCandidate] = []
    raw_actions: list[dict[str, object]] = []

    for line in lines:
        candidate = _extract_from_line(line, properties, contacts, links, reference_time)
        if candidate is None:
            continue
        candidates.append(candidate)
        raw_actions.append(
            {
                "source_line": candidate.source_line,
                "action_type": candidate.action_type,
                "title": candidate.title,
                "property_id": candidate.property_id,
                "contact_id": candidate.contact_id,
                "contact_role": candidate.contact_role,
                "starts_at": candidate.starts_at.isoformat() if candidate.starts_at else None,
                "ends_at": candidate.ends_at.isoformat() if candidate.ends_at else None,
                "due_at": candidate.due_at.isoformat() if candidate.due_at else None,
                "confidence_label": candidate.confidence_label,
                "unresolved_fields": candidate.unresolved_fields,
            }
        )

    if not candidates:
        fallback = DraftCandidate(
            property_id=None,
            contact_id=None,
            contact_role=None,
            action_type="generic_follow_up",
            title="Review call and capture next step",
            description=(transcript_text.strip() or "No transcript text available.")[:400],
            starts_at=None,
            ends_at=None,
            due_at=reference_time + timedelta(days=1),
            confidence_label="low",
            unresolved_fields=["property_id", "contact_id"],
            source_line=transcript_text.strip() or "No transcript text available.",
        )
        candidates.append(fallback)
        raw_actions.append(
            {
                "source_line": fallback.source_line,
                "action_type": fallback.action_type,
                "title": fallback.title,
                "property_id": None,
                "contact_id": None,
                "contact_role": None,
                "starts_at": None,
                "ends_at": None,
                "due_at": fallback.due_at.isoformat() if fallback.due_at else None,
                "confidence_label": fallback.confidence_label,
                "unresolved_fields": fallback.unresolved_fields,
            }
        )

    return candidates, {"actions": raw_actions, "line_count": len(lines)}


def _candidate_lines(transcript_text: str) -> list[str]:
    segments = re.split(r"[\r\n]+|(?<=[.!?])\s+", transcript_text)
    cleaned = [segment.strip(" \t-*•") for segment in segments if segment.strip(" \t-*•")]
    return cleaned[:25]


def _extract_from_line(
    line: str,
    properties: list[Property],
    contacts: list[Contact],
    links: list[PropertyContactLink],
    reference_time: datetime,
) -> DraftCandidate | None:
    normalized = line.lower()
    if len(normalized) < 8:
        return None

    property_match = _match_property(normalized, properties)
    contact_match = _match_contact(normalized, contacts)
    inferred_role = _detect_role(normalized)
    if contact_match is None and property_match is not None and inferred_role is not None:
        contact_match = _contact_for_property_role(property_match.id, inferred_role, contacts, links)

    action_type = _detect_action_type(normalized)
    if action_type is None:
        return None

    parsed_time = _parse_timing(normalized, reference_time)
    starts_at: datetime | None = None
    ends_at: datetime | None = None
    due_at: datetime | None = None
    if action_type == "property_visit":
        if parsed_time.get("scheduled_at") is not None:
            starts_at = parsed_time["scheduled_at"]
            ends_at = starts_at + timedelta(hours=1)
        else:
            due_at = parsed_time.get("due_at")
    else:
        due_at = parsed_time.get("due_at") or parsed_time.get("scheduled_at")

    unresolved_fields: list[str] = []
    if property_match is None:
        unresolved_fields.append("property_id")
    if contact_match is None:
        unresolved_fields.append("contact_id")
    if starts_at is None and due_at is None:
        unresolved_fields.append("timing")

    confidence_points = 1
    if property_match is not None:
        confidence_points += 1
    if contact_match is not None:
        confidence_points += 1
    if starts_at is not None or due_at is not None:
        confidence_points += 1

    confidence_label = "high" if confidence_points >= 4 else "medium" if confidence_points >= 3 else "low"
    title = _build_title(action_type, property_match, contact_match, inferred_role)
    description = line[:500]

    return DraftCandidate(
        property_id=property_match.id if property_match else None,
        contact_id=contact_match.id if contact_match else None,
        contact_role=inferred_role or _role_from_link(property_match.id if property_match else None, contact_match.id if contact_match else None, links),
        action_type=action_type,
        title=title,
        description=description,
        starts_at=starts_at,
        ends_at=ends_at,
        due_at=due_at,
        confidence_label=confidence_label,
        unresolved_fields=unresolved_fields,
        source_line=line,
    )


def _match_property(text: str, properties: list[Property]) -> Property | None:
    matches = [
        property_
        for property_ in properties
        if property_.title.lower() in text or property_.address_line_1.lower() in text
    ]
    if not matches:
        return None
    matches.sort(key=lambda property_: max(len(property_.title), len(property_.address_line_1)), reverse=True)
    return matches[0]


def _match_contact(text: str, contacts: list[Contact]) -> Contact | None:
    matches = [contact for contact in contacts if contact.full_name.lower() in text]
    if not matches:
        return None
    matches.sort(key=lambda contact: len(contact.full_name), reverse=True)
    return matches[0]


def _detect_role(text: str) -> str | None:
    if "seller" in text:
        return "seller"
    if "buyer" in text:
        return "buyer"
    return None


def _contact_for_property_role(
    property_id: str,
    role: str,
    contacts: list[Contact],
    links: list[PropertyContactLink],
) -> Contact | None:
    role_links = [link for link in links if link.property_id == property_id and link.role.lower() == role.lower()]
    if len(role_links) != 1:
        return None
    contact_id = role_links[0].contact_id
    for contact in contacts:
        if contact.id == contact_id:
            return contact
    return None


def _role_from_link(property_id: str | None, contact_id: str | None, links: list[PropertyContactLink]) -> str | None:
    if property_id is None or contact_id is None:
        return None
    for link in links:
        if link.property_id == property_id and link.contact_id == contact_id:
            return link.role
    return None


def _detect_action_type(text: str) -> str | None:
    if any(keyword in text for keyword in ["visit", "showing", "site visit", "property tour"]):
        return "property_visit"
    if any(keyword in text for keyword in ["follow up", "follow-up", "call back", "callback", "check back", "decision"]):
        return "follow_up"
    if "document" in text or "formalit" in text:
        return "document_check"
    if "reply" in text or "respond" in text:
        return "reply"
    if "confirm" in text or "check with" in text:
        return "confirmation"
    return None


def _build_title(action_type: str, property_match: Property | None, contact_match: Contact | None, inferred_role: str | None) -> str:
    property_fragment = f" for {property_match.title}" if property_match else ""
    if action_type == "property_visit":
        if contact_match:
            return f"Property visit with {contact_match.full_name}{property_fragment}"
        return f"Schedule property visit{property_fragment}"
    if action_type == "follow_up":
        if contact_match:
            return f"Follow up with {contact_match.full_name}{property_fragment}"
        if inferred_role:
            return f"Follow up with {inferred_role}{property_fragment}"
        return f"Follow up on call{property_fragment}"
    if action_type == "document_check":
        if inferred_role == "seller":
            return f"Confirm required documents with seller{property_fragment}"
        return f"Confirm required documents{property_fragment}"
    if action_type == "reply":
        if contact_match:
            return f"Reply to {contact_match.full_name}{property_fragment}"
        return f"Reply to contact{property_fragment}"
    return f"Confirm next step{property_fragment}"


def _parse_timing(text: str, reference_time: datetime) -> dict[str, datetime | None]:
    scheduled_at = _parse_absolute_datetime(text)
    if scheduled_at is not None:
        return {"scheduled_at": scheduled_at, "due_at": scheduled_at}

    due_at: datetime | None = None
    if "tomorrow" in text:
        due_at = reference_time + timedelta(days=1)
    elif "today" in text:
        due_at = reference_time
    else:
        days_match = re.search(r"(?:in|after)\s+(\d+)(?:\s*-\s*\d+)?\s+days?", text)
        if days_match is not None:
            due_at = reference_time + timedelta(days=int(days_match.group(1)))
        elif "next week" in text:
            due_at = reference_time + timedelta(days=7)

    return {"scheduled_at": None, "due_at": due_at}


def _parse_absolute_datetime(text: str) -> datetime | None:
    date_match = re.search(r"(20\d{2}-\d{2}-\d{2})", text)
    if date_match is None:
        return None

    date_value = date_match.group(1)
    time_match = re.search(r"(?:at\s+)?(\d{1,2})(?::(\d{2}))?\s*(am|pm)?", text)
    hour = 9
    minute = 0
    if time_match is not None:
        hour = int(time_match.group(1))
        minute = int(time_match.group(2) or 0)
        meridiem = time_match.group(3)
        if meridiem == "pm" and hour != 12:
            hour += 12
        if meridiem == "am" and hour == 12:
            hour = 0

    try:
        return datetime.fromisoformat(f"{date_value}T{hour:02d}:{minute:02d}:00").replace(tzinfo=UTC)
    except ValueError:
        return None